// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqCnOnK5_XrvNPIKuP-78CcIAswrHd9Uk',
    appId: '1:52372229418:web:f172ae04b857f79f076253',
    messagingSenderId: '52372229418',
    projectId: 'finsmart-e8df4',
    authDomain: 'finsmart-e8df4.firebaseapp.com',
    storageBucket: 'finsmart-e8df4.appspot.com',
    measurementId: 'G-HW2BBXPNRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ug04_apQ-vJTPpKWMUQEhejDttG2lc8',
    appId: '1:52372229418:android:07130b99457e4a9a076253',
    messagingSenderId: '52372229418',
    projectId: 'finsmart-e8df4',
    storageBucket: 'finsmart-e8df4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGHRJFFwep1ndEKGTbdgrytF6dVfXd-fE',
    appId: '1:52372229418:ios:4dd73b99a8b655a3076253',
    messagingSenderId: '52372229418',
    projectId: 'finsmart-e8df4',
    storageBucket: 'finsmart-e8df4.appspot.com',
    iosClientId: '52372229418-mhpseffkj6v6nd93h449jfrbrbg5gftr.apps.googleusercontent.com',
    iosBundleId: 'com.example.hecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGHRJFFwep1ndEKGTbdgrytF6dVfXd-fE',
    appId: '1:52372229418:ios:4dd73b99a8b655a3076253',
    messagingSenderId: '52372229418',
    projectId: 'finsmart-e8df4',
    storageBucket: 'finsmart-e8df4.appspot.com',
    iosClientId: '52372229418-mhpseffkj6v6nd93h449jfrbrbg5gftr.apps.googleusercontent.com',
    iosBundleId: 'com.example.hecker',
  );
}
